### ISSUE TITLE
BE: Need to create 'VolunteerTeam' entity so that a team of volunteers can perform rescue missions together

### ISSUE THREAD

**Issue by skfarhad** [skfarhad/hazard_reporting_system#15]
Need to create 'VolunteerTeam' entity. If volunteers want to perform perform rescue missions together, this should be added. There will 'team_leader' and 'member' of that  'VolunteerTeam'. SMS instructions will go to the 'team_leader' instead of all the members separately.

**Comment by TasfiqulGhani** [comment]
PR: https://github.com/skfarhad/hazard_reporting_system/pull/50
