### ISSUE TITLE
BE: Add 'validation_status' property with Incident model

### ISSUE THREAD

**Issue by skfarhad** [skfarhad/hazard_reporting_system#18]
Need to add 'validation_status' property with Incident model with choices "pending", "validated" and "rejected".
It's needed so that garbage data can be rejected before performing volunteer matching algorithm. The validation process will be manual.

**Comment by TasfiqulGhani** [comment]
This issue will be resolved in this PR: https://github.com/skfarhad/hazard_reporting_system/pull/33

**Comment by skfarhad** [comment]
Resolved in PR: https://github.com/skfarhad/hazard_reporting_system/pull/33
