### ISSUE TITLE
BE: Add "district" & "thana" properties with Incident model

### ISSUE THREAD

**Issue by skfarhad** [skfarhad/hazard_reporting_system#20]
Need to add "district" & "thana" properties with Incident model so that Incidents can be filtered easily according those properties.
The values of District and & Thana will come from `District` and `Thana` models.

```
ADMIN_AREA = {
   "Feni": [
      "Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"
  ]
......
}
```
Need to validate so that the District -Thana combination is consistent.

**Comment by MuhammadAdil00600** [comment]
Can I work on this issue?

**Comment by skfarhad** [comment]
> Can I work on this issue?

Sure!

**Comment by TasfiqulGhani** [comment]
This PR https://github.com/skfarhad/hazard_reporting_system/pull/31 will resolve this issue.
CC: @MuhammadAdil00600 Bhai , @skfarhad  Bhai
