### ISSUE TITLE
BE: Add "district" & "thana" properties with Volunteer model

### ISSUE THREAD

**Issue by skfarhad** [skfarhad/hazard_reporting_system#23]
Need to add "district" & "thana" properties with Volunteer model so that Volunteers can be filtered easily according those properties.
The values of District and & Thana will come from District and Thana models.

ADMIN_AREA = {
   "Feni": [
      "Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"
  ]
......
}
Need to validate so that the District -Thana combination is consistent.

**Comment by TasfiqulGhani** [comment]
PR Added: https://github.com/skfarhad/hazard_reporting_system/pull/31

**Comment by skfarhad** [comment]
Implemented by this PR: https://github.com/skfarhad/hazard_reporting_system/pull/50
