### ISSUE TITLE
DevOps: Setting up the Kubernetes cluster & possibly use Ansible Playbook for the provision

### ISSUE THREAD

**Issue by SifatIbna** [skfarhad/hazard_reporting_system#28]
Description:
Install and configure a Kubernetes cluster on our managed server. This is the first step in our infrastructure setup. Possible

Tasks:
- [x] Choose Kubernetes distribution
- [x] Install chosen Kubernetes distribution on the managed server
- [ ] Configure networking
- [x] Set up control plane and worker nodes
- [x] Verify cluster is operational with basic commands (kubectl get nodes, etc.)
- [x] Document installation process and configuration

**Comment by ashraf-minhaj** [comment]
k8s version 1.30.4
