### ISSUE TITLE
BE: TemplateDoesNotExist bug on django admin panel form

### ISSUE THREAD

**Issue by md-abdul-alim** [skfarhad/hazard_reporting_system#56]
Django admin panel error.

This error occurred where **models.MultiPolygonField** django model field used. This is happing when opening the model form in django admin.

To fix this error we have to add "django.contrib.gis" in INSTALLED_APPS list. 

<img width="950" alt="image" src="https://github.com/user-attachments/assets/6029460d-4818-4f58-b956-953b034b050a">

**Comment by skfarhad** [comment]
Added the dependency
